name: template
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Networking
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Library for creating mock objects in Dart tests
  mocktail: ^1.0.4
  # Generate unique ids for testing purposes
  uuid: ^4.4.2

flutter:
  uses-material-design: true

  fonts:
    - family: SpaceMono
      fonts:
        - asset: assets/fonts/space_mono/SpaceMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/space_mono/SpaceMono-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/space_mono/SpaceMono-Italic.ttf
          style: italic
        - asset: assets/fonts/space_mono/SpaceMono-Regular.ttf
