name: template
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SpaceMono
      fonts:
        - asset: assets/fonts/space_mono/SpaceMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/space_mono/SpaceMono-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/space_mono/SpaceMono-Italic.ttf
          style: italic
        - asset: assets/fonts/space_mono/SpaceMono-Regular.ttf
